FROM resin/rpi-raspbian
MAINTAINER Matias Schertel <mschertel@gmail.com>

# Environment
ENV DEBIAN_FRONTEND=noninteractive

# Upgrade system
RUN apt-get update && apt-get upgrade -y

# Install debconf
RUN apt-get -y install apt-utils

# Locale config
RUN apt-get -y install locales && \
    locale-gen en_US.UTF-8 && \
    dpkg-reconfigure locales

RUN apt-get -y install nano

RUN apt-get -y install openssh-server && \
    apt-get -y install git

# Remove unecessary files
RUN apt-get autoremove -y && apt-get autoclean -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# To avoid annoying "perl: warning: Setting locale failed." errors,
# do not allow the client to pass custom locals, see:
# http://stackoverflow.com/a/2510548/15677
RUN sed -i 's/^AcceptEnv\ LANG LC_\*/\#AcceptEnv\ LANG LC_\*/g' /etc/ssh/sshd_config

RUN mkdir /var/run/sshd

# Create git user
RUN adduser --system --home /home/git --shell /bin/bash --group --disabled-password --disabled-login git && \
    su git -c "mkdir /home/git/bin"

# Install gitolite
RUN cd /home/git; su git -c "git clone git://github.com/sitaramc/gitolite";
RUN cd /home/git; su git -c "gitolite/install -ln";

# https://github.com/docker/docker/issues/5892
RUN chown -R git:git /home/git

# http://stackoverflow.com/questions/22547939/docker-gitlab-container-ssh-git-login-error
RUN sed -i '/session    required     pam_loginuid.so/d' /etc/pam.d/sshd

# Forbid SSH password auth for git user
RUN echo "" >> /etc/ssh/sshd_config && \
    echo "# Gitolite changes from $(date)" >> /etc/ssh/sshd_config && \
    echo "Match User git" >> /etc/ssh/sshd_config && \
    echo "    PasswordAuthentication no" >> /etc/ssh/sshd_config

# Remove SSH host keys, so they will be generated by /init
RUN rm -f /etc/ssh/ssh_host_*

ADD ./init.sh /init

# Addind volume to repositories directory
VOLUME /home/git/repositories
VOLUME /etc/ssh

RUN chmod +x /init
ENTRYPOINT ["/init", "/usr/sbin/sshd", "-D"]

EXPOSE 22
